### ISSUE TITLE
update of tz_world at runtime

### ISSUE THREAD

**Issue by jnyrup** [mj1856/GeoTimeZone#26]
Would it be possible to update tz_world at runtime in order to have an updated world view without having to update GeoTimeZone on a running instance?
Similiar to [NodaTime](http://nodatime.org/1.3.x/userguide/tzdb.html)

**Comment by mj1856** [comment]
This is possible, sure.  It would involve reading the `TZ.dat` and `TZL.dat` files from the file system instead of using the embedded versions.  I'll consider that for a future release.

One thing though - the boundary maps change much less frequently than the tz data, because usually changes are to DST rules of existing zones.  Boundary maps only change when either the border changes, or when *part* of an existing zone changes, thus splitting one zone into two.

Given that, wouldn't it just be easier to pull the new version down from nuget and redeploy?  It's not something you'll have to do that often, IMHO.

**Comment by jnyrup** [comment]
Thanks for your detailed comments and for the consideration.

Yes, it is easier to do the manual update and redeploy - at least the first few times.
Then it becomes tedious and at least I wants to automate the process :)

**Comment by mj1856** [comment]
I've decided against implementing this.  If it's still important for you, consider a fork or an add-on library.  Thanks.
