### ISSUE TITLE
Nuget installation issues targeting .Net Framework 4.5.2 and lower.

### ISSUE THREAD

**Issue by KozyLigh** [mj1856/GeoTimeZone#27]
Greetings,

I tried to add GeoTimeZone to my web api project and I get the following error: 
Could not install package 'System.Runtime 4.0.20'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thank you for your help

With regards,

Marko

**Comment by mj1856** [comment]
I'm surprised to say because I tested thoroughly before publishing to Nuget, but I too can reproduce this issue.  I also have a similar issue when targeting .NET 4.0 applications.  For some reason, installing from nuget.org is behaving differently than the local installation I used during testing.  I have opened an issue for this at NuGet/Home#4228.

Ultimately the problem is that the PCL version is being ignored.  Only the netstandard version is used.

As a temporary workaround, consider one of the following:

- Install with `Install-Package GeoTimeZone -IgnoreDependencies`.  There really are no required dependencies with .NET Framework other than the built-in support from mscorlib.

- Upgrade to .Net Framework 4.6.1 or 4.6.2 - These seem to work fine with the `netstandard` support.

- Convert to .net core - more drastic, but the version being installed is working there.

**Comment by jnyrup** [comment]
From the dependencies listed on [NuGet](https://www.nuget.org/packages/System.Runtime)

* 4.0.10: .NETFramework 4.5.1
* 4.0.20: .NETFramework 4.6
* 4.1.0 : .NETFramework 4.5, .NETFramework 4.6.2
* 4.3.0 : .NETFramework 4.5, .NETFramework 4.6.2

So there seems to be some weird dependency typo for v4.0.20.

**Comment by mj1856** [comment]
This should no longer be an issue with the repackaging done in version 3.0.0.  Thanks.

**Comment by yeganehaym** [comment]
i got this error too when i'm installing from nuget
Could not install package 'MiniProfiler.Mvc5 4.0.138'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2'

**Comment by SaraBenShabbat** [comment]
Hi,
I have this error also. Thanks for the answer. But how I Upgrade to .Net Framework 4.6.1 or 4.6.2 & how I 
convert to .net core ?? 
furthermore, Hoe can I know what's the version of my project ??
Please, answer! It's very very urgent!
Thanks a lot!!
