### ISSUE TITLE
Timezone incorrect for Africa/Ceuta

### ISSUE THREAD

**Issue by KaPtainCugel** [mj1856/GeoTimeZone#42]
Hi,

the following code should return Africa/Ceuta, but instead returns Africa/Casablanca:
	double latitude = 35.8894012908865;
	double longitude = -5.30445597754788; 
	Console.WriteLine(TimeZoneLookup.GetTimeZone(latitude, longitude).Result);
I checked the time zone in OpenStreetMap: https://www.openstreetmap.org/relation/1154756#map=7/35.885/-5.317

**Comment by mj1856** [comment]
This is due to the encoding accuracy, discussed previously in #10, #24 #34, etc.

The part of Ceuta where this point is located is less than 1km wide.  The surrounding waters in are part of `Africa/Casablanca` (Morocco) in the TBB map data.

![image](https://user-images.githubusercontent.com/1396388/63462093-02adaa00-c40f-11e9-8a19-147268e17c2e.png)

**Comment by mattjohnsonpint** [comment]
Please provide feedback on the precision issue here: #56
Thanks!
